README.md
epoch_api/epoch_api.md
epoch_api/oracle_api.md
oracles/oracle_state_tree.md
oracles/oracle_ws_api.md
oracles/oracles.md

WebSocket API and life cycle example using the API

Pt 154245674 oracle api

---

epoch_api/account_api_usage.md
epoch_api/epoch_api.md
epoch_api/spend_api_usage.md

I am moving here items out of the epoch release notes that constitute intended usage.

Document intented usage of account&spend -related API

---

drafts/AENS.md

This is the draft for the first version of the AENS.
Comments and questions are welcome.

first draft for the AENS

---

epoch/api/README.md
epoch/api/chain_ws_api.md
epoch/api/oracle_ws_api.md

Chain WS actions:
* get block by height/hash
* get header by height/hash
* push notification for mining a block

Chain WS API

---

oracles/oracle_state_tree.md

Remove requirement on order of some operations

---

epoch/api/naming_system_api_usage.md

* Use GET /commitment-hash
* Change the domain to the one that is valid
This depends on https://github.com/aeternity/epoch/pull/697.
[Delivers #154872121]

PT-154872121 Improve Naming System intended usage

---

README.md
contracts/aevm.md
contracts/contract_life_cycle.md
contracts/contract_state_tree.md
contracts/contract_transactions.md
contracts/contracts.md
contracts/ring.md
contracts/sophia.md
epoch/api/README.md
epoch/api/contract_api_usage.md

Inital specification of smart contracts.

Pt 154173179 contract spec

---

epoch/api/oracle_ws_api.md
oracles/oracle_state_tree.md
oracles/oracle_transactions.md
oracles/oracles.md

https://www.pivotaltracker.com/story/show/155428127
and https://www.pivotaltracker.com/story/show/155025536
and some more generic updates

Updated oracle specs + added extend oracle TX

---

contracts/sophia.md

Fixed some outdated information and added specification of the (current) syntax.

PT-155286626 enrich contract docs

---

epoch/api/account_api_usage.md

Relates to aeternity/epoch#944.

Point the account balance example at the new external API location

---

contracts/aevm.md
contracts/contract_transactions.md
contracts/contract_vms.md
contracts/contracts.md
contracts/solidity.md
contracts/sophia.md
contracts/varna.md

The ABI version is built in to the vm_version field.

Pt 155763999 add ABI field to contracts

---

contracts/contract_state_tree.md
serializations.md

More strict definition of tree objects.
Goes with epoch PR https://github.com/aeternity/epoch/pull/1064

Calls are now stored in a separate tree. 

---

serializations.md

[Tags](https://github.com/aeternity/epoch/blob/a22ffa239f3ef63126410cadb3bad66f5efed1b0/apps/aecore/src/aec_object_serialization.erl#L73-L81)
[Create transaction template](https://github.com/aeternity/epoch/blob/a22ffa239f3ef63126410cadb3bad66f5efed1b0/apps/aechannel/src/aesc_create_tx.erl#L214-L223)
[Deposit transaction template](https://github.com/aeternity/epoch/blob/a22ffa239f3ef63126410cadb3bad66f5efed1b0/apps/aechannel/src/aesc_deposit_tx.erl#L178-L184)
[Withdraw transaction template](https://github.com/aeternity/epoch/blob/a22ffa239f3ef63126410cadb3bad66f5efed1b0/apps/aechannel/src/aesc_withdraw_tx.erl#L180-L186)
[Close mutual transaction template](https://github.com/aeternity/epoch/blob/a22ffa239f3ef63126410cadb3bad66f5efed1b0/apps/aechannel/src/aesc_close_mutual_tx.erl#L188-L194) …

Channel serializations

---

epoch/api/README.md
epoch/api/channels_api_usage.md

Addressing comments from [PR68](https://github.com/aeternity/protocol/pull/68)

Channels intended usage polish

---

epoch/api/channels_api_usage.md

[Pivotal story](https://www.pivotaltracker.com/story/show/157599298)
This is the protocol update for PR [Channels: new WebSocket events and tests](https://github.com/aeternity/epoch/pull/1135) and adds description for the different update errors, the conflicts and generic messages sending

Channels: new WebSocket events

---

epoch/api/account_api_usage.md

Addressing changes from aeternity/epoch#1142

Adapt documentation to new HTTP API

---

serializations.md

Delivers https://www.pivotaltracker.com/story/show/157626157

Clarify determinism of serialization of tx with multiple signatures

---

serializations.md

The new serialization introduced in https://github.com/aeternity/epoch/pull/1131

Update to new contract serialization with balance in account tree.

---

serializations.md

In scope of https://www.pivotaltracker.com/story/show/157308030
Not ready to be merged until related code is ready.

Remove unneeded height from account

---

epoch/api/channels_api_usage.md

Addressing changes introduced by aeternity/epoch#1153

Channels intended usage: WS broadcast of on-chain txs

---

channels/ON-CHAIN.md
serializations.md

https://www.pivotaltracker.com/n/projects/2124891/stories/157695429

Pt 157695429 remove 'from' field in close mutual

---

CONSENSUS.md
contracts/sophia.md
serializations.md

In scope of https://www.pivotaltracker.com/story/show/157214052

Move coinbase to header

---

AENS.md

Delivers https://www.pivotaltracker.com/story/show/154836584

Remove explicit non-miner fee in name claim tx as inconsistent

---

serializations.md

PR prepared while checking https://github.com/aeternity/epoch/pull/1180

Update and detail channel offchain tx

---

serializations.md

https://github.com/aeternity/epoch/pull/1202
https://www.pivotaltracker.com/n/projects/2124891/stories/157873700

Add Proof of inclusion serialization

---

SYNC.md
sync/p2p_messages.md

Delivers https://www.pivotaltracker.com/story/show/157624784

Initial sync documentation

---

contracts/contract_transactions.md

Prepared while reading for https://www.pivotaltracker.com/story/show/154664693

Review gas-related doc

---

epoch/api/chain_ws_api.md

In scope of https://www.pivotaltracker.com/story/show/157998007

Clarify chain WebSocket user API re block events

---

README.md
serializations.md

* Link serializations.md from README.md
* Remove the id from some objects
https://www.pivotaltracker.com/n/projects/2124891/stories/158071477

Describe serializations of identifiers

---

serializations.md

Spec update for proposal at https://www.pivotaltracker.com/story/show/154664693/comments/190227856

Enrich contract call state tree object with gas price

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
epoch/api/channels_api_usage.md
serializations.md

Changes corresponding to aeternity/epoch#1241
As you can see `Initial state` of the intended API usage is much simpler now

Adapting channels to recent changes

---

contracts/sophia.md

For [PT-158183507](https://www.pivotaltracker.com/story/show/158183507).
See also https://github.com/aeternity/epoch/pull/1256

Documentation of maps

---

contracts/contract_transactions.md
serializations.md

Delivers https://www.pivotaltracker.com/story/show/158430391

Update spec of contract key generation

---

contracts/contract_transactions.md
contracts/contract_vms.md

Delivers https://www.pivotaltracker.com/story/show/158528153

Clarify misleading duplicated contract txs serialization doc

---

serializations.md

In scope of https://www.pivotaltracker.com/story/show/158520766
Supersedes #125 
Maybe TODO:
* Tracked as https://www.pivotaltracker.com/story/show/158630078

Contract proof of inclusion improvements

---

epoch/api/channels_api_usage.md

Changes corresponding to aeternity/epoch#1276

Add channel's intended usage for deposit/withdrawal

---

epoch/api/channels_api_usage.md

Reverts aeternity/protocol#126

Revert "Add channel's intended usage for deposit/withdrawal"

---

sync/p2p_messages.md

Aligned to https://github.com/aeternity/epoch/pull/1293

Align network serialization doc to initial Bitcoin NG in epoch

---

contracts/sophia.md

Companion PR: https://github.com/aeternity/epoch/pull/1283

Document Sophia AENS primitives

---

epoch/api/channel_ws_api.md
epoch/api/oracle_ws_api.md

[State channels WebSocket API schema](https://www.pivotaltracker.com/story/show/157476849)
Based on PR #126 so it should be merged first

Channels ws api schema

---

epoch/api/channels_api_usage.md

[Describe solo closing sequence](https://www.pivotaltracker.com/story/show/158580163)
This is based on top of #126 and it must be included before merging this one.

Pt 158580163 channels solo closing

---

contracts/sophia.md

Epoch PR: https://github.com/aeternity/epoch/pull/1320

PT-158762346 Sophia variant types

---

contracts/sophia.md

In scope of https://www.pivotaltracker.com/story/show/158982822
Please review alongside https://github.com/aeternity/epoch/pull/1334

Refresh Sophia example from epoch master

---

channels/ON-CHAIN.md
channels/README.md
serializations.md

Protocol update in correspondence of aeternity/epoch#1325

Add serialization and description for the channel_snapshot_solo_tx

---

channels/ON-CHAIN.md
epoch/api/channels_api_usage.md
serializations.md

Channels' closing amounts refactoring

---

channels/ON-CHAIN.md
serializations.md

This PR addresses changes made in aeternity/epoch#1308

Add channels' delegates

---

GOSSIP.md
sync/p2p_messages.md

Update the documentation to reflect the implementation from https://github.com/aeternity/epoch/pull/1252 .

Update peer pool documentation after implementation

---

channels/OFF-CHAIN.md
channels/README.md
epoch/api/channels_api_usage.md
serializations.md

Corresponding protocol changes for aeternity/epoch#1385

Contracts in a channel description

---

epoch/api/channels_api_usage.md

This reverts commit 06f572df108ce812771850f6f88139c4e5136261.

Revert "Add channel's WS API usage: getting of balances, poi and contract calls"

---

epoch/api/channels_api_usage.md

Channels ws api balances

---

epoch/api/contract_api_usage.md

Mention user API for contract create tx with Sophia args

Pt 159587547 contract create compute

---

epoch/api/channels_api_usage.md

Changes corresponding to aeternity/epoch#1432

Prune channel contract calls

---

contracts/contract_transactions.md

In scope of https://www.pivotaltracker.com/story/show/159735602
This is optional clarification in doc, and goes alongside tests in https://github.com/aeternity/epoch/pull/1438

Note amount transfer in case of contract call failure

---

contracts/sophia.md

Add types to list examples.

---

contracts/sophia.md

Companion of https://github.com/aeternity/epoch/pull/1457.

Document type aliases

---

oracles/oracle_transactions.md

Delivers https://www.pivotaltracker.com/story/show/159134505

Deduplicate oracle txs serializations doc

---

contracts/sophia.md

Companion PR for https://github.com/aeternity/epoch/pull/1479

PT-160016525 contract types

---

contracts/aevm.md

Delivers https://www.pivotaltracker.com/story/show/159919056
It should have been part of doc update PR #163 alongside code PR https://github.com/aeternity/epoch/pull/1439

Update AEVM primops doc following oracle query fee updates

---

channels/OFF-CHAIN.md

PT [Protocol: revisit channel closing section](https://www.pivotaltracker.com/story/show/159365180)

Revisit the closing section

---

epoch/api/chain_ws_api.md

WS API fixes

---

consensus/consensus.md
serializations.md

https://www.pivotaltracker.com/story/show/160166518

Update to new serialization format of micro blocks and headers

---

contracts/sophia.md

Companion PR for https://github.com/aeternity/epoch/pull/1493

Document oracle TTL type

---

contracts/aevm.md

Update protocol to reflect that a COINBASE instruction returns the beneficiary of previous keyblock.

Document COINBASE.

---

GOSSIP.md
SYNC.md
epoch/api/account_api_usage.md
epoch/api/chain_ws_api.md
epoch/api/channel_ws_api.md
epoch/api/channels_api_usage.md
epoch/api/naming_system_api_usage.md
epoch/api/oracle_api_usage.md

Solves https://www.pivotaltracker.com/story/show/160254986

Replace '$' with '_' in addresses

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
channels/README.md
serializations.md

Corresponding protocol changed describing aeternity/epoch#1469

Force progress

---

consensus/bitcoin-ng.md
serializations.md

https://www.pivotaltracker.com/story/show/155700135
https://github.com/aeternity/epoch/pull/1557

Pt 155700135 proof of fraud

---

contracts/contract_transactions.md

Clarification PR companion of [this ticket comment](https://www.pivotaltracker.com/story/show/160669401/comments/194480176).
It applies to:
https://www.pivotaltracker.com/story/show/160669401
https://www.pivotaltracker.com/story/show/160671392
https://www.pivotaltracker.com/story/show/160671577

Document that contract transaction is not implemented yet

---

consensus/consensus.md

[PT-160129190](https://www.pivotaltracker.com/n/projects/2124891/stories/160129190)

 PT-160129190 Change accepted future block time shift from 10 to 9 min

---

contracts/sophia.md

For [PT-160377912](https://www.pivotaltracker.com/story/show/160377912).

Update Sophia ABI description

---

channels/ON-CHAIN.md
channels/README.md

This PR introduces no semantic changes to the state channels and is only meant to make the text easier to follow.

state channels, minor text cleanups

---

serializations.md

Refine state channels doc

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
contracts/aevm.md

Changes related to aeternity/epoch#1592

Describe usage of on-chain objects in off-chain contracts

---

epoch/api/README.md
epoch/api/mining_api_usage.md

[PT-160981321](https://www.pivotaltracker.com/n/projects/2124891/stories/160981321)

PT-160981321 Add intended usage of mining API

---

consensus/consensus.md

[PT-160256699](https://www.pivotaltracker.com/n/projects/2124891/stories/160256699)

PT-160256699 Mention gas limit per micro block

---

contracts/sophia.md

This is refers to [PT-160993470](https://www.pivotaltracker.com/story/show/160993470)

Abort is now a built-in function and should not be defined by user

---

contracts/sophia.md
serializations.md

https://www.pivotaltracker.com/story/show/155763919

Add description of sophia byte code meta data

---

consensus/consensus.md

In scope of https://www.pivotaltracker.com/story/show/160262754
This goes alongside https://github.com/aeternity/epoch/pull/1638

Align consensus version doc to code

---

contracts/contract_transactions.md

Companion PR of https://github.com/aeternity/epoch/pull/1661

Update contract txs doc re upfront charges

---

contracts/sophia.md

See https://github.com/aeternity/epoch/blob/615c1f2726c71fc1c914e385e8096dd7b1d114d8/apps/aesophia/src/aeso_ast_to_icode.erl#L139
Found while working on https://www.pivotaltracker.com/story/show/160671577 though independent.

Fix name of contract primitive for balance

---

contracts/sophia.md

See https://github.com/aeternity/epoch/pull/1679

PT-161380219: Add check to disallow reentrant calls for Sophia EVM

---

serializations.md

Prepared while reviewing https://github.com/aeternity/epoch/pull/1649

Clarify serialization of proof of inclusion

---

contracts/solidity.md
serializations.md

Delivers https://www.pivotaltracker.com/story/show/161153684

Fix duplicated Sophia store spec

---

epoch/api/contract_api_usage.md

Companion of https://github.com/aeternity/epoch/pull/1709

PT-160256544 Document new calldata creation

---

contracts/contract_vms.md
oracles/oracle_transactions.md
oracles/oracles.md
serializations.md

https://www.pivotaltracker.com/story/show/153819317

Describe oracle vm version, response and query formats

---

epoch/api/README.md
epoch/api/api_encoding.md
epoch/api/channels_api_usage.md

https://www.pivotaltracker.com/story/show/161616592

Add description of the API encoding scheme of binary data

---

contracts/contract_transactions.md

Epoch: https://github.com/aeternity/epoch/pull/1736
Pivotal: [PT-161507006](https://www.pivotaltracker.com/story/show/161507006)

Value transfer is refunded on contract failure

---

contracts/sophia.md

Epoch: https://github.com/aeternity/epoch/pull/1753

Update type of abort and clarify semantics

---

AENS.md
epoch/api/naming_system_api_usage.md
serializations.md

Alongside https://github.com/aeternity/epoch/pull/1767 delivers https://www.pivotaltracker.com/story/show/158026916

Detail AENS pointers

---

contracts/contract_vms.md
contracts/solidity.md
epoch/api/contract_api_usage.md

Not too happy about the wording about Solidity - maybe we should remove more?! Suggestions are welcome.

Dry-run and disable Solidity EVM 

---

consensus/consensus.md
contracts/aevm.md
oracles/oracle_transactions.md

[PT-161778582](https://www.pivotaltracker.com/n/projects/2124891/stories/161778582)
Adds gas docs for transactions and updates gas docs for primops (base gas was missing).

PT-161778582 Update gas in txs and primops

---

channels/OFF-CHAIN.md

See [PT #162416632](https://www.pivotaltracker.com/story/show/162416632).

describe microblock confirmations

---

contracts/contract_vms.md
oracles/oracle_transactions.md

Covers both:
* https://www.pivotaltracker.com/story/show/162792344
* https://www.pivotaltracker.com/story/show/162376008

Remove deprecated VMs and describe changes to AEVM_02

---

contracts/sophia.md

Pivotal: [PT-163362624](https://www.pivotaltracker.com/story/show/163362624)
Bytecode: https://github.com/aeternity/aebytecode/pull/3
Compiler: https://github.com/aeternity/aesophia/pull/12
Aeternity: https://github.com/aeternity/aeternity/pull/2039

PT-163362624 generic hash functions

---

GOSSIP.md
README.md
SYNC.md
channels/OFF-CHAIN.md
node/api/README.md
node/api/api_encoding.md
node/api/channels_api_usage.md
node/api/contract_api_usage.md
node/api/mining_api_usage.md
node/api/naming_system_api_usage.md
node/api/oracle_api_usage.md
node/api/spend_api_usage.md
sync/p2p_messages.md
sync/tx_pool_sync.md

Delivers https://www.pivotaltracker.com/story/show/163321210

Amend docs content re renaming

---

contracts/sophia.md

Documentation for https://github.com/aeternity/aesophia/pull/17

PT-163478903 builtin bits type

---

node/api/naming_system_api_usage.md

https://www.pivotaltracker.com/story/show/163859290

Names should be api encoded in claim transaction api

---

contracts/sophia.md

Pivotal: [PT-156466783](https://www.pivotaltracker.com/story/show/156466783)
Sophia: https://github.com/aeternity/aesophia/pull/25

PT-156466783 namespaces

---

consensus/consensus.md
node/api/mining_api_usage.md
serializations.md

https://www.pivotaltracker.com/story/show/164062750

Pt 164062750 add info field to key header

---

node/api/channels_api_usage.md

Complementary to aeternity/aeternity#2127, opened against `minerva` and superseded #303

Sc ws dry run call

---

node/api/channel_ws_api_json-rpc.md

Result of [comment](https://github.com/aeternity/aeternity/pull/2205#discussion_r263019999)

Added a new JSON-RPC error code

---

node/api/api_encoding.md
node/api/channel_ws_api.md

Complimentary to [aeternity/aeternity#2046](https://github.com/aeternity/aeternity/pull/2046)

[PT-159406140] Get latest channel state

---

node/api/api_encoding.md
node/api/channel_ws_api.md

Documentation for aeternity/aeternity#2232

PT-159405994 get channel contract state

---

node/api/channel_ws_api.md

Documentation for aeternity/aeternity#2239
This also adds docs for `channel.update.new_contract` and `channel.update.call_contract` methods.

PT-159405636 Add channel ws contract methods docs

---

contracts/contract_state_tree.md
serializations.md

In scope of https://www.pivotaltracker.com/story/show/164539296

Document that field log in contract is always empty

---

node/api/channel_ws_api_json-rpc.md

Complementary to aeternity/aeternity#2279

SC WS new JSON-RPC error code: invalid number

---

serializations.md

Complementary to aeternity/aeternity#2316

Describe pinned block on-chain serializations

---

node/api/channels_api_usage.md

Documentation for aeternity/aeternity#2335

PT-159714644 Get channels parameters from chain in reestablish

---

channels/ON-CHAIN.md
channels/README.md
contracts/contract_state_tree.md
contracts/contract_transactions.md
contracts/contract_vms.md
contracts/sophia.md
generalized_accounts/generalized_accounts.md
oracles/oracles.md
serializations.md

- describe serialization 
- stub for generalized accounts description (cc @knarz )
- add `Auth.tx_hash` to Sophia description
- add a note to channel create
- misc fixes

Generalized Accounts

---

contracts/sophia.md

~~TODO: address literal syntax/scan/parse. (cc @UlfNorell )~~
Also this PR aims to further clarify the format of literals.

Add bytes(Len) and use base58 encoded address literals

---

serializations.md

PT [SC: Remove pinned env from FP and offchain tx](https://www.pivotaltracker.com/story/show/165593706)
This is the protocol part of the ticket, basically reverting #337
`aeternity` node's part is in aeternity/aeternity#2358

Remove pinned env

---

generalized_accounts/generalized_accounts.md

This is the protocol specification for generalised accounts.

generalised accounts spec

---

channels/OFF-CHAIN.md

Corresponding changes for aeternity/aeternity#2369

Describe off-chain protocol pinned env

---

consensus/bitcoin-ng.md

Prepared while reviewing https://github.com/aeternity/aeternity/pull/2343 - for clarifying state before that PR.
Last known state of past discussions:
* https://github.com/aeternity/protocol/pull/201#discussion_r218380643
* https://www.pivotaltracker.com/story/show/160585630/comments/194893336

Document what fraud reward is proportional to

---

contracts/sophia.md

Added `Address.is_contract`, `Address.is_oracle`, `Oracle.check` and `Oracle.check_query`.
And a note on `Contract.creator`...

Add address check primitives

---

consensus/bitcoin-ng.md

Following review of #345
Put together during preparation of #350

Rewards clarifications

---

consensus/consensus.md
node/api/api_encoding.md

https://www.pivotaltracker.com/story/show/165993503 and https://www.pivotaltracker.com/story/show/165853843

Misc fixes - byte array, minumum fee, etc

---

consensus/consensus.md

PT [SC FP minimum base gas bump](https://www.pivotaltracker.com/story/show/166001363), complementary to aeternity/aeternity#2426

Bump FP gas price

---

node/api/README.md

[Pivotal](https://www.pivotaltracker.com/story/show/159459679)
Aeternity PR: aeternity/aeternity#2429

Added new SC WS error codes

---

consensus/bitcoin-ng.md

Alternative to #345
The idea is to have the text ready so we can merge when/if needed.

Details of rewards including rewards split

---

contracts/sophia.md

cc https://github.com/aeternity/aesophia/pull/69

Document stateful checks

---

consensus/consensus.md

Correct signature info

---

contracts/sophia.md
contracts/sophia_explained.md

This is planned to be a place to add more in-depth discussion on Sophia topics...

Add Sophia Explained

---

node/api/channels_api_usage.md

as part of [Fine-tune state channels for Fortuna](https://www.pivotaltracker.com/story/show/166114135)

Describe details of GAs and channels

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Complementary changes for aeternity/aeternity#2484

Describe the ping-pong mechanism

---

node/api/channel_ws_api.md

Prepared while reviewing https://github.com/aeternity/aeternity/pull/2484

Fix channels API markup as shown on GitHub

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
channels/authentication.md
node/api/channel_ws_api.md
node/api/channels_api_usage.md

Changes corresponding to aeternity/aeternity#2502

Explain GAs in State Channel FSM

---

node/api/README.md
node/api/channels_api_usage.md

Documentation regardin /aeternity/aeternity#2560

Define WebSocket opening errors

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Protocol changes regarding aeternity/aeternity#2574

Describe SC WS variable renaming

---

channels/OFF-CHAIN.md
node/api/channels_api_usage.md

Documentation for [PT #167194534](https://www.pivotaltracker.com/story/show/167194534) and [aeternity PR #2572](https://github.com/aeternity/aeternity/pull/2572)

Add info on SC port multiplexing support

---

AENS.md

Prepared while reviewing spec for an AENS enhancement.

Remove AENS claim requirement not actually enforced in code

---

node/api/channels_api_usage.md

Adapt according to [code](https://github.com/aeternity/aeternity/blob/master/apps/aetx/src/aetx.erl#L422-L426).

Fix documentation inconsistency

---

node/api/channels_api_usage.md

Complementary to aeternity/aeternity#2597

Describing timeouts' messages

---

node/api/channels_api_usage.md

`s/signature/authentication` as it sounds more GA-ish
also while being there I reformated the text to 80 chars limit

Some polish

---

node/api/channels_api_usage.md
node/api/examples/channels/json-rpc/reconnect/sc_ws_basic_client_reconnect_i.md
node/api/examples/channels/json-rpc/reconnect/sc_ws_basic_client_reconnect_r.md

Documentation PR for https://github.com/aeternity/aeternity/pull/2611
Includes updated examples from the improved client reconnect test cases.

Add backchannel updates to channels_api_usage.md

---

contracts/sophia.md
serializations.md

Add description of payable + new serializations.

PT-162578406 Add payable modifier

---

contracts/sophia.md

Add info about ecrecover and ecverify

---

node/api/channel_ws_api.md
node/api/examples/channels/json-rpc/continuous/sc_ws_update_conflict.md

See [PT #168160333](https://www.pivotaltracker.com/story/show/168160333)
More documentation will follow

Initial docs on SC signing error replies

---

contracts/sophia.md

And also added one missing newline

Added tuple type to grammar

---

contracts/sophia_stdlib.md

<s>This waits for `d26fcace41a84fadef7e532a2f585832977967b7` aesophia commit to be included in the release</s>

Added stdlib docs

---

contracts/sophia.md

Mention overflow and underflow in arithmetic operation documentation

---

contracts/fate.md

Updated the documentation of FATE and smart-contract features based on the following article:
https://read.wearedevelopers.com/aeternity-devs-are-taking-moores-law-into-the-realm-of-code-faster-execution-smaller-code-size/

Described design goals of FATE

---

contracts/contract_vms.md
contracts/sophia.md

Doing this towards @happi's PR #279

Update the information about VMs

---

contracts/sophia.md

This waits for https://github.com/aeternity/aesophia/pull/105 to be merged.
While you are inspecting this PR – where should docs for standard library go? Imo here they will take too much space in sophia.md...

Mentioned standard library and list comprehensions

---

generalized_accounts/ga_explained.md

Supersedes #386 (solves the merge conflict).

Update ECDSA GA example

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Complementary to aeternity/aeternity#2885

State Channels: on-chain fees

---

channels/README.md

Related to aeternity/aeternity#2823
Config parameters affecting state channels are summarized in the README

Add configuration info in channels/README.md

---

AENS.md
serializations.md

Please see discussion in old PR: https://github.com/aeternity/protocol/pull/379

AENS protocol update for auctions

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Pt 168289008 sc soft reject 2

---

channels/ON-CHAIN.md
channels/state.md

Fix slash inconsitencies and add a section regarding what channel state is

Improve SC docs

---

consensus/consensus.md
generalized_accounts/generalized_accounts.md
serializations.md

Associated to https://github.com/aeternity/aeternity/pull/2999
Also fixes some obviously incorrect values.

GH-2851 Docs for PayingForTx

---

contracts/sophia.md

See aeternity/aesophia#194 and aeternity/aesophia#196.

Updated Sophia grammar and added example of lhs pattern matching

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Complementary RP to aeternity/aeternity#3077

Describe SC optional gas price

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Changes corresponding to aeternity/aeternity#3126

Describe optional nonces in FSM API

---

contracts/sophia.md
contracts/sophia_explained.md

Also show some examples for AENS.lookup in sophia_explained.md

Add AENS.update, AENS.lookup and Oracle.expiry to sophia.md

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Complementary changes to PR aeternity/aeternity#3147

Describe Force progress production

---

contracts/sophia.md

- Issue: aeternity/aesophia#203
- aeternity/aebytecode#93
- aeternity/aesophia#241
- aeternity/aeternity#3162

Document protected calls

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Complementary PR to aeternity/aeternity#3197

Describe malicious FP detection

---

node/api/channels_api_usage.md

Corresponding changes to PR aeternity/aeternity#3120

Describe update errors in FSM

---

generalized_accounts/generalized_accounts.md
serializations.md

This is a complementary PR to aeternity/aeternity#3416.

Remove Meta tx TTL

---

sync/p2p_messages.md

This is a complementary PR to aeternity/aeternity#3423.
The work on this PR is supported by the Aeternity Crypto Foundation.

Describe the p2p info message

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md
node/api/examples/channels/json-rpc/assume_min_depth/sc_ws_basic_open_close.md

See PR aeternity/aeternity#3521 and aeternity/aeternity#3555
This documents the behavior of the new `channels.assume_minimum_depth` method.

Document channels.assume_minimum_depth method

---

serializations.md

Related changes: aeternity/aeternity#3546

Clarify Init function strip before Iris

---

AENS.md

Document the stricter AENS pointer checks

---

GOSSIP.md

Related to https://github.com/aeternity/aeternity/pull/3135

Update gossip doc

---

channels/ON-CHAIN.md
serializations.md

Complementary to aeternity/aeternity#3543

Describe set delegates

---

node/api/channels_api_usage.md

Documentation for PR aeternity/aeternity#3634
This PR is supported by the Aeternity Crypto Foundation

Add documentation on minimum depth

---

consensus/README.md

Clarify inner_tx signature for PayingForTx

---

contracts/fate.md

Iris: Update lists for FATE operations

---

consensus/README.md

GH-492 Clarify byte_size in dynamic gas cost

---

contracts/contract_transactions.md
contracts/contract_vms.md
serializations.md

Related to https://github.com/aeternity/aeternity/pull/4009 and https://github.com/aeternity/aeternity/pull/4016

GH-4009: Contract call by name + general CERES updates

---

README.md

Does this change require governance mechanisms to be involved?

Remove outdated disclaimer

---

.github/workflows/requirements.txt

getting annoyed of dependency issues here. I shortly checked locally and it should work now

chore: update mkdocs dependencies

---

AENS.md

Documents aeternity/aeternity#4056 (and aeternity/aesophia#426)

GH-4056 [Ceres]: AENS add raw data pointers

---

generalized_accounts/README.md
serializations.md

Documents aeternity/aeternity#4057

GH-4057 [Ceres]: Tamper protection for GAMetaTx

---

contracts/contract_vms.md
contracts/fate.md

[Ceres]: Update FATE documentation (operations, etc.)

---

.gitignore
AENS.md

+ renamed a few: hard-fork ==> protocol upgrade 😅 

Document the extended max expiry for AENS names

---

generalized_accounts/README.md

Documents aeternity/aeternity#4237
This PR is supported by Æternity Foundation

[Ceres] Add GAAttachTx restriction

---

AENS.md

[Ceres] Optional preclaim + updated auction parameters

---

serializations.md

Added a few missing parts of the serialization process.
The changes comply with the actual serialization code in `aebytecode` repository.

Update serialization docs

---

serializations.md

Fixes #521.
This PR is supported by Æternity Foundation

Document raw data pointer serialization

---

node/api/channels_api_usage.md

This PR is supported by the Æternity Foundation

Channel docs fixes
