AENS.md

The variable previously called nonce it completely arbitrary,
so it seems to be clearer when we call it salt

Naming adjustment

---

epoch/api/account_api_usage.md

We have a new Client's `GET /account/balance/{account_pubkey}` API endpoint.
It replaces the old API for getting the balance which used to be part of the external gossip protocol.
[PR of the epoch change](https://github.com/aeternity/epoch/pull/679)

Replace old /account/balance with the new one

---

epoch/api/README.md

Operator may implement HTTPS.
See also https://github.com/aeternity/protocol/pull/57#discussion_r177994828

Remove mention of HTTPS for epoch API

---

epoch/api/channels_api_usage.md
epoch/api/oracle_api_usage.md

... so to reduce likelihood of user targeting wrong port.
Follows https://github.com/aeternity/epoch/commit/ec95eb566c75a6818ff6a645f532173401fea6df
In scope of https://www.pivotaltracker.com/story/show/157112368

Amend user doc to use default ports

---

channels/ON-CHAIN.md

Add requirement and explain TTL is absolute
It must be an absolute TTL, because the transaction is in the mempool and therefore relative to a block on chain makes no sense.

One more requirement on creating a channel on chain.

---

channels/ON-CHAIN.md

channel_id is needed as input of several API operations. Added an explanation on how to compute it and a link to epoch where this is done.

Mention computation of channel id 

---

contracts/contract_state_tree.md

Error introduced in https://github.com/aeternity/protocol/pull/111/commits/3a0fb9a775f2643e99728c4158aef47e22a3af84

Correct documented key of call object in state trees

---

epoch/api/channel_ws_api.md
epoch/api/channels_api_usage.md

See [PT #159405858](https://www.pivotaltracker.com/story/show/159405858).
Note also that `channel_id` has been added in at least some reports (to make it easier to store `channel_id` + `offchain_tx` – the two elements needed to be able to reestablish a channel.

document leave/reestablish API

---

consensus/consensus.md

For the purpose of generating the header hash, that is used as a key for hashing in the cuckoo cycle algorithm, the evidence and nonce are set to all `0`. This is currently not documented anywhere other than in a comment in the code.

clarifies the process to generate header hash for pow

---

epoch/api/channels_api_usage.md

@ThomasArts had discovered an inconsistency in WebSocket API and protocol description.
The channel's WebSocket parameters are read [here](https://github.com/aeternity/epoch/blob/master/apps/aehttp/src/sc_ws_handler.erl#L599-L600)
This PR does not address the description of resuming the connection to an old preexisting channel (the reconnect to client). This is tracked as [Document in protocol opening a WebSocket for an existing channel](https://www.pivotaltracker.com/story/show/160339328)

Apply parameter changes in channel opening messages

---

epoch/api/channels_api_usage.md

It is the `initiator` that has to provide the `host` and `port` of the `responder`.

Fix error in channels spec

---

contracts/sophia.md

... as not defined anywhere in the document and - based on code
inspection - not recognized by parser.

Replace reference to `unit` type (alias for tuple with zero elements)

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
serializations.md

Related to PT #160591670
In the related PR to epoch, the `channel_close_mutual_tx` definition was changed. This PR adjusts the documentation accordingly, and also fixes a few errors found in the process.

Update channel_close_mutual definition + fix some misnamings and typos

---

channels/OFF-CHAIN.md
channels/ON-CHAIN.md
channels/README.md
serializations.md

This PR removes the lock period from channels while they are open and instead keeps track of two different round numbers. It also tries to clarify handling of disputes in the different states of a channel.

removes lock from channel in open state

---

epoch/api/README.md
epoch/api/channels_api_usage.md

Addressing [this](https://github.com/aeternity/epoch/pull/1667#discussion_r226312373) comment.
Also some clarifications and bug fixes.
Somehow the initiator and responder addresses ended up not base58 decodable
```
(epoch@localhost)5> aec_base58c:decode(<<"ak_4Kr76woCtc3ehZ45K1sCrmgKX6gnh7qGhjSU1GZYqfLTTjtCgn">>).
** exception error: incorrect_size
in function  aec_base58c:decode/1 (/home/vlz/projects/aeternity/epoch/_build/prod/lib/aecore/src/aec_base58c.erl, line 54)
```

Channels' interfaces descriptions

---

contracts/sophia.md

Remove `uint` since it's not yet present in Sophia.

Remove `uint` from the docs.

---

AENS.md

Both Roma and Minerva accept name updates that have a TTL of 50000 blocks into the future.

Bring protocol in line with real world

---

node/api/channels_api_usage.md

PT: [SC: document timeouts in API](https://www.pivotaltracker.com/story/show/164897506)
All timeouts' keys and defaults are described [here](https://github.com/aeternity/aeternity/blob/master/apps/aechannel/src/aesc_fsm.erl#L282-L290). Please note that `timeout_open` does not make much sense outside of the scope of `timeout_idle` and I plan on removing it from `aesc_fsm:timeouts()` so it [falls back to `idle` timeout value](https://github.com/aeternity/aeternity/blob/master/apps/aechannel/src/aesc_fsm.erl#L262). This will change the default value for it from 12000 ms to 600000 ms but since those are defaults, I don't consider it an API breaking change.

Describe State Channel WebSocket timeouts

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

See [PT #166056472](https://www.pivotaltracker.com/story/show/166056472)

Initial docs addition of close_solo and settle

---

STRATUM.md

This adds a specification for a stratum protocol, that allows mining pool operators to delegate work among a group of connected workers.

adds a stratum specification

---

node/api/channels_api_usage.md
serializations.md

Alternative to #387 - documenting the use of `round` in the reconnect_tx in order to guard against replay attacks. See https://github.com/aeternity/aeternity/pull/2603

Pt 167617278 allow sc ws to disconnect 2

---

node/api/channel_ws_api.md
node/api/channels_api_usage.md

Proof-reading corrections to PR #447 - primarily adding a section about `slash` in the `channel_ws_api.md` docs.

Add slash section in api, correct typos

---

GOSSIP.md

There were some changes:
* a new peer to establish a connection to is now always selected from verified pool first;
* max number of peers is 32;
* peers in ping message are selected from verified pool only.
This PR updates the doc so it reflects the implementation.

Reflect the current state of gossip

---

AENS.md
channels/OFF-CHAIN.md
consensus/README.md
consensus/locking.md
contracts/aevm.md
contracts/contract_state_tree.md
contracts/fate.md
node/api/README.md
node/api/account_api_usage.md
node/api/channel_ws_api.md
node/api/channels_api_usage.md
node/api/spend_api_usage.md

Change tokens to coins where appropriate

---

consensus/README.md

docs: remove unused notation from consensus readme

---

sync/p2p_messages.md

This PR is supported by Æternity Foundation and Æternity Crypto Foundation

Add ping version 2 description.

---

AENS.md
serializations.md

With raw data pointers version 2 must be used, and without raw data pointers version 1 must be used.
Addresses aeternity/aeternity#4365
This PR is supported by the Æternity Foundation

Clarify and correct docs on AENSUpdateTx

---

contracts/fate.md

The pipe operator caused the table to misdisplay. Also it is a bit non-standard as it can mean alternative outside Erlang/Prolog communities.

Fix formatting of CONS fate instruction doc
